# Generated by Django 3.2.9 on 2021-12-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('confirm', models.CharField(max_length=25)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('hobbies', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('address', models.TextField(max_length=125)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
